### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by davidseek** [adamontherun/SpotifyTokenRefresh#2]
I beg you. Please explain to me, why this is working...
When I just enter my information into the Heroku script, it is working perfectly.

When I pull the files from your Git, enter my information and push it to heroku, my own Server is not working. I'm getting: `JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.`

http://stackoverflow.com/questions/40813928/how-to-properly-handle-token-refresh-with-spotify-sdk-and-swift-3-error-code-38

With your service it is working, but I would like to know how and why. What is the difference?

Literally all I do is:

```
$ heroku login
$ git add .
$ git commit -am "make it better"
$ git push heroku master
```

Everything seems to work...

```
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rack
remote: -----> Using Ruby version: ruby-2.2.0
remote: -----> Installing dependencies using bundler 1.13.6
blah blah blah
```

But inApp, only your version is working. I would like to understand my mistake... Please take the minute and explain. Also you can answer in the Stackoverflow Thread... 50 Reps Bounty, 15 Answer and 10 upvote awaiting you...

Thank you.

**Comment by adamontherun** [comment]
Hi David, I'm sorry you're having problems. 

I'm not a Ruby or Heroku expert so I don't know why that's happening. My guess is that its related to the 'Deploy with Heroku' button that I used to deploy the code. Have you researched that yet?

**Comment by davidseek** [comment]
I have tried this crap like forever. With 100 Billion different scripts (that kinda all did the same). With your `Deploy with Heroku` Button it is working and I freaking don't get why... 

I don't even know what that Button is. I have never done anything with Heroku, I just came up with that a month ago when I badly tried it implement the Token swap... I mean, I'm glad that it is working. But how and why... 

Too bad that you can't help. But thank you.
